const web3ActionTypes = {
	INSTANTIATE_WEB3: 'INSTANTIATE_WEB3',
	WEB3_ON_SUCCESS: 'WEB3_ON_SUCCESS',
	SET_ACCOUNTS: 'SET_ACCOUNTS',
	SET_CONTRACT: 'SET_CONTRACT',
	ON_INSTANTIATION_ERROR: 'ON_INSTANTIATION_ERROR',
};

export default web3ActionTypes;
